name = "raxnet-prime"
main = "functions/_worker.ts"
compatibility_date = "2024-08-15"

[env.production]
d1_databases = [
  { binding = "DB", database_name = "raxnet-prime-db", database_id = "" }
]

[env.preview]
d1_databases = [
  { binding = "DB", database_name = "raxnet-prime-db-preview", database_id = "" }
]

# Pages functions
pages_build_output_dir = "dist"

# Build command for Pages
[build]
command = "npm run build"

# Environment variables
[vars]
NODE_ENV = "production"
